[project]
	type = "plugin"
	name = "ozone-plugin"
	description = "Ozone debugger plugin"
	version = "3.10.0" 
	
	entrypoint = "ozone_plugin/build.py"

[packaging]
	include = [
		"ozone_plugin",
		"ozone"
	]
	exclude = [
		"*.pyc"
	]